version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go build -o bin/web ./cmd/web && ./bin/web -dsn='web:pass@tcp(db:3306)/goapi?parseTime=true' -addr=':8080'"
    environment:
      - DB_HOST=db
      - DB_USER=web
      - DB_PASSWORD=pass
      - DB_NAME=movies4u
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: movies4u
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "web", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
